<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting" Version="13.4.6"/>
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10"/>
        <PackageReference Include="OpenTelemetry" Version="1.17.0"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.17.0"/>
        <PackageReference Update="SonarAnalyzer.CSharp" Version="10.30.0.144632">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Update="Meziantou.Analyzer" Version="3.0.130">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.302">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Daedalus.Infrastructure/Daedalus.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
