namespace Daedalus.Application.Commands.RegeneratePlan;

/// <summary>
///     Result of a plan regeneration operation.
/// </summary>
/// <param name="PlanFilePath">The full path to the regenerated fix_plan.md file.</param>
/// <param name="PlanContent">The new plan content generated by the LLM.</param>
/// <param name="PreviousPlanBackedUp">Whether the previous plan was backed up before regeneration.</param>
public record RegeneratePlanResult(
    string PlanFilePath,
    string PlanContent,
    bool PreviousPlanBackedUp);
