global using System.Net;
global using System.Net.Http.Json;
global using AwesomeAssertions;
global using ZeroAlloc.Results;
global using NSubstitute;
global using NSubstitute.ExceptionExtensions;
global using Spectre.Console;
global using Spectre.Console.Testing;
global using Xunit;
