<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <!-- Suppress code analysis warnings for test project -->
        <NoWarn>
            $(NoWarn);CA1707;CA1012;CA1051;CA1033;CA1024;CA1055;CA1822;CA1721;MA0017;MA0016;MA0002;MA0009;S3442;S2325;S1481;S2699;CS0612;CS8605;S1144;CA1001;CA1054;CA1307;CA1305;MA0011;MA0110;SYSLIB1045;S1125;CA1508;CA1823;CA2234
        </NoWarn>
        <!-- Disable trimming for tests -->
        <TrimMode>none</TrimMode>
        <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="AwesomeAssertions"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Microsoft.Playwright"/>
        <PackageReference Include="Microsoft.Playwright.NUnit"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit3TestAdapter"/>
        <PackageReference Include="Testcontainers"/>
        <PackageReference Include="Testcontainers.PostgreSql"/>
        <PackageReference Include="Npgsql"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Daedalus.Api\Daedalus.Api.csproj"/>
        <ProjectReference Include="..\..\src\Daedalus.Application\Daedalus.Application.csproj"/>
        <ProjectReference Include="..\..\src\Daedalus.Domain\Daedalus.Domain.csproj"/>
        <ProjectReference Include="..\..\src\Daedalus.Infrastructure\Daedalus.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\src\Daedalus.Web\Daedalus.Web.csproj"/>
    </ItemGroup>

</Project>
