using Daedalus.Domain.Entities;

namespace Daedalus.Application.DTOs;

/// <summary>
///     Represents a PRD item (task requirement) generated by the LLM.
/// </summary>
public record PrdItemDto(
    string Title,
    string Description,
    string AcceptanceCriteria,
    Priority Priority,
    Complexity EstimatedComplexity,
    int DependenciesCount = 0,
    IReadOnlyList<string>? Dependencies = null,
    string Phase = "Implementation",
    int ParallelGroup = 1);
