#pragma warning disable S1144 // EF Core sets RowVersion via reflection (unused private setter is required)

using ZeroAlloc.Results;

namespace Daedalus.Domain.Entities;

/// <summary>
///     A unit of work on a project's board. A person starts a manufacture run for it, and its status is then derived
///     from that run when it is read (phase 2.8). Tasks from before phase 2.8 keep the status and the execution
///     history the retired task loop recorded.
/// </summary>
public sealed class Task : AggregateRoot<Guid>
{
    private readonly List<string> _dependencies = [];
    private readonly List<TaskExecution> _executions = [];
    private readonly List<string> _filesToModify = [];

    /// <summary>Gets the task identifier string (e.g., "TASK-001").</summary>
    public string TaskId { get; private set; } = string.Empty;

    /// <summary>Gets the parent project ID.</summary>
    public Guid ProjectId { get; private set; }

    /// <summary>Gets the task title.</summary>
    public string Title { get; private set; } = string.Empty;

    /// <summary>Gets the task description.</summary>
    public string Description { get; private set; } = string.Empty;

    /// <summary>Gets the priority level.</summary>
    public Priority Priority { get; private set; } = Priority.Medium;

    /// <summary>
    ///     Gets the task's stored status. Reads show the derived status instead, which <c>TaskStatusDerivation</c> maps
    ///     from the task's manufacture run; the stored value shows only when the task has no readable run.
    /// </summary>
    public TaskStatus Status { get; private set; } = TaskStatus.Pending;

    /// <summary>Gets the phase/stage of the project (e.g., "Backend", "Frontend").</summary>
    public string Phase { get; private set; } = string.Empty;

    /// <summary>Gets the parallel group for task scheduling.</summary>
    public int ParallelGroup { get; private set; } = 1;

    /// <summary>Gets task IDs this task depends on.</summary>
    public IReadOnlyList<string> Dependencies => _dependencies.AsReadOnly();

    /// <summary>Gets file paths that will be modified by this task.</summary>
    public IReadOnlyList<string> FilesToModify => _filesToModify.AsReadOnly();

    /// <summary>Gets the estimated complexity of the task.</summary>
    public Complexity EstimatedComplexity { get; private set; } = Complexity.Medium;

    /// <summary>Gets the prompt to be repeatedly sent to the LLM.</summary>
    public string Prompt { get; private set; } = string.Empty;

    /// <summary>Gets the completion promise. Set only by the task loop that phase 2.8 retired. A task created since has none: empty and 0.</summary>
    public string CompletionPromise { get; private set; } = string.Empty;

    /// <summary>Gets the maximum iterations. Set only by the task loop that phase 2.8 retired. A task created since has none: empty and 0.</summary>
    public int MaxIterations { get; private set; }

    /// <summary>Gets the session currently executing this task, if any.</summary>
    public Guid? CurrentSessionId { get; private set; }

    /// <summary>Gets the final result/output from the LLM when completed.</summary>
    public string? Result { get; private set; }

    /// <summary>Gets the number of iterations completed.</summary>
    public int IterationCount { get; private set; }

    /// <summary>Gets when the task was created.</summary>
    public DateTime CreatedAt { get; private set; } = DateTime.UtcNow;

    /// <summary>Gets when the task completed or failed.</summary>
    public DateTime? CompletedAt { get; private set; }

    /// <summary>Gets all execution records (iterations attempted).</summary>
    public IReadOnlyList<TaskExecution> Executions => _executions.AsReadOnly();

    /// <summary>Gets accumulated learnings from previous executions of this task.</summary>
    public string Learnings { get; private set; } = string.Empty;

    /// <summary>Gets when learnings were last updated.</summary>
    public DateTime? LearningsUpdatedAt { get; private set; }

    /// <summary>
    ///     Gets the concurrency token for optimistic locking: the PostgreSQL <c>xmin</c> system column, which the
    ///     database advances on every write. A <c>byte[]</c> row version is never generated by Postgres, so it would
    ///     never be enforced. Prevents a stale save from overwriting a newer row, such as the attached run.
    /// </summary>
    public uint RowVersion { get; private set; }

    /// <summary>
    ///     Gets the id of the manufacture run most recently started for this task, or null when none was. Earlier runs
    ///     stay in the workflow run history. The task's status is derived from this run when the task is read.
    /// </summary>
    public Guid? WorkflowRunId { get; private set; }

    /// <summary>
    ///     Creates a new task within a project.
    /// </summary>
    public static Result<Task> Create(
        Guid id,
        Guid projectId,
        string taskId,
        string title,
        string description,
        Priority priority,
        string phase,
        int parallelGroup,
        Complexity estimatedComplexity,
        string prompt,
        DateTime? createdAt = null)
    {
        if (string.IsNullOrWhiteSpace(taskId))
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Task ID cannot be empty");
        }

        if (taskId.Length > 50)
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Task ID cannot exceed 50 characters");
        }

        if (string.IsNullOrWhiteSpace(title))
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Title cannot be empty");
        }

        if (title.Length > 500)
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Title cannot exceed 500 characters");
        }

        if (string.IsNullOrWhiteSpace(description))
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Description cannot be empty");
        }

        if (description.Length > 2000)
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Description cannot exceed 2000 characters");
        }

        if (string.IsNullOrWhiteSpace(phase))
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Phase cannot be empty");
        }

        if (phase.Length > 100)
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Phase cannot exceed 100 characters");
        }

        if (string.IsNullOrWhiteSpace(prompt))
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Prompt cannot be empty");
        }

        if (prompt.Length > 8000)
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Prompt cannot exceed 8000 characters");
        }

        if (parallelGroup < 1)
        {
            return ZeroAlloc.Results.Result<Task>.Failure("Parallel group must be at least 1");
        }

        return ZeroAlloc.Results.Result<Task>.Success(new Task
        {
            Id = id,
            ProjectId = projectId,
            TaskId = taskId.Trim(),
            Title = title.Trim(),
            Description = description.Trim(),
            Priority = priority,
            Phase = phase.Trim(),
            ParallelGroup = parallelGroup,
            EstimatedComplexity = estimatedComplexity,
            Prompt = prompt.Trim(),
            CreatedAt = createdAt ?? DateTime.UtcNow
        });
    }

    /// <summary>
    ///     Adds a dependency on another task.
    /// </summary>
    public Result AddDependency(string dependsOnTaskId)
    {
        if (string.IsNullOrWhiteSpace(dependsOnTaskId))
        {
            return ZeroAlloc.Results.Result.Failure("Dependency task ID cannot be empty");
        }

        if (string.Equals(dependsOnTaskId, TaskId, StringComparison.Ordinal))
        {
            return ZeroAlloc.Results.Result.Failure("A task cannot depend on itself");
        }

        if (_dependencies.Contains(dependsOnTaskId, StringComparer.Ordinal))
        {
            return ZeroAlloc.Results.Result.Failure($"Task already depends on {dependsOnTaskId}");
        }

        _dependencies.Add(dependsOnTaskId);
        return ZeroAlloc.Results.Result.Success();
    }

    /// <summary>
    ///     Removes a dependency.
    /// </summary>
    public Result RemoveDependency(string dependsOnTaskId)
    {
        if (string.IsNullOrWhiteSpace(dependsOnTaskId))
        {
            return ZeroAlloc.Results.Result.Failure("Dependency task ID cannot be empty");
        }

        if (!_dependencies.Contains(dependsOnTaskId, StringComparer.Ordinal))
        {
            return ZeroAlloc.Results.Result.Failure($"Task does not depend on {dependsOnTaskId}");
        }

        _dependencies.Remove(dependsOnTaskId);
        return ZeroAlloc.Results.Result.Success();
    }

    /// <summary>
    ///     Adds a file to be modified by this task.
    /// </summary>
    public Result AddFileToModify(string filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
        {
            return ZeroAlloc.Results.Result.Failure("File path cannot be empty");
        }

        if (_filesToModify.Contains(filePath, StringComparer.Ordinal))
        {
            return ZeroAlloc.Results.Result.Failure($"File {filePath} already added");
        }

        _filesToModify.Add(filePath.Trim());
        return ZeroAlloc.Results.Result.Success();
    }

    /// <summary>
    ///     Removes a file from the modification list.
    /// </summary>
    public Result RemoveFileToModify(string filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
        {
            return ZeroAlloc.Results.Result.Failure("File path cannot be empty");
        }

        if (!_filesToModify.Contains(filePath, StringComparer.Ordinal))
        {
            return ZeroAlloc.Results.Result.Failure($"File {filePath} not found");
        }

        _filesToModify.Remove(filePath);
        return ZeroAlloc.Results.Result.Success();
    }

    /// <summary>
    ///     Records <paramref name="runId"/> as this task's current manufacture run, replacing any earlier one. The stored
    ///     <see cref="Status"/> is not changed: it is derived from the run when the task is read.
    /// </summary>
    public Result AttachRun(Guid runId)
    {
        if (runId == Guid.Empty)
        {
            return ZeroAlloc.Results.Result.Failure("Run id cannot be empty");
        }

        WorkflowRunId = runId;
        return ZeroAlloc.Results.Result.Success();
    }

    /// <summary>
    ///     Updates task metadata (title, description, priority, etc).
    /// </summary>
    public Result UpdateMetadata(
        string title,
        string description,
        Priority priority,
        string phase,
        Complexity complexity)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            return ZeroAlloc.Results.Result.Failure("Title cannot be empty");
        }

        if (title.Length > 500)
        {
            return ZeroAlloc.Results.Result.Failure("Title cannot exceed 500 characters");
        }

        if (string.IsNullOrWhiteSpace(description))
        {
            return ZeroAlloc.Results.Result.Failure("Description cannot be empty");
        }

        if (description.Length > 2000)
        {
            return ZeroAlloc.Results.Result.Failure("Description cannot exceed 2000 characters");
        }

        if (string.IsNullOrWhiteSpace(phase))
        {
            return ZeroAlloc.Results.Result.Failure("Phase cannot be empty");
        }

        if (phase.Length > 100)
        {
            return ZeroAlloc.Results.Result.Failure("Phase cannot exceed 100 characters");
        }

        Title = title.Trim();
        Description = description.Trim();
        Priority = priority;
        Phase = phase.Trim();
        EstimatedComplexity = complexity;
        return ZeroAlloc.Results.Result.Success();
    }

    /// <summary>
    ///     Updates the parallel group and the prompt.
    /// </summary>
    public Result UpdateExecutionConfig(
        int? parallelGroup = null,
        string? prompt = null)
    {
        if (parallelGroup.HasValue)
        {
            if (parallelGroup.Value < 1)
            {
                return ZeroAlloc.Results.Result.Failure("Parallel group must be at least 1");
            }

            ParallelGroup = parallelGroup.Value;
        }

        if (prompt is not null)
        {
            if (string.IsNullOrWhiteSpace(prompt))
            {
                return ZeroAlloc.Results.Result.Failure("Prompt cannot be empty");
            }

            if (prompt.Length > 8000)
            {
                return ZeroAlloc.Results.Result.Failure("Prompt cannot exceed 8000 characters");
            }

            Prompt = prompt.Trim();
        }

        return ZeroAlloc.Results.Result.Success();
    }
}
#pragma warning restore S1144
