using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Daedalus.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MakeTaskRowVersionXmin : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // The bytea RowVersion was never generated by Postgres, so it enforced nothing. The Task now uses the
            // xmin system column, which every table already has: nothing to add.
            migrationBuilder.DropColumn(
                name: "RowVersion",
                table: "Tasks");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<byte[]>(
                name: "RowVersion",
                table: "Tasks",
                type: "bytea",
                rowVersion: true,
                nullable: true);
        }
    }
}
