// <auto-generated />
using System;
using System.Collections.Generic;
using Daedalus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Daedalus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816174546_AddAgentSessions")]
    partial class AddAgentSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.AnalysisIteration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<Guid>("CodeAnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<bool?>("CompilationSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PromptSent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("TestsPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CodeAnalysisRequestId")
                        .HasDatabaseName("IX_AnalysisIteration_RequestId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AnalysisIteration_CreatedAt");

                    b.ToTable("AnalysisIterations");
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionPromise")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentIteration")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalReferences")
                        .HasColumnType("jsonb");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("FeatureBranchName")
                        .HasColumnType("text");

                    b.Property<string>("LastAiResponse")
                        .HasColumnType("text");

                    b.Property<string>("LastPromptSent")
                        .HasColumnType("text");

                    b.Property<string>("LocalWorkTreePath")
                        .HasColumnType("text");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ReferencedDocuments")
                        .HasColumnType("jsonb");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CodeAnalysis_CreatedAt");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_CodeAnalysis_Priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CodeAnalysis_Status");

                    b.ToTable("CodeAnalysisRequests");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("IX_AgentMessage_Session_Sequence");

                    b.ToTable("AgentMessages", (string)null);
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("TotalInputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalOutputTokens")
                        .HasColumnType("bigint");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("IX_AgentSession_AgentId");

                    b.HasIndex("OwnerId", "CreatedAt")
                        .HasDatabaseName("IX_AgentSession_Owner_CreatedAt");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.BrainstormMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrainstormSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrainstormSessionId")
                        .HasDatabaseName("IX_BrainstormMessage_SessionId");

                    b.ToTable("BrainstormMessages", (string)null);
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.BrainstormSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesignDocument")
                        .HasColumnType("text");

                    b.Property<string>("ImplementationPlan")
                        .HasColumnType("text");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<bool>("PhaseCompleteSignaled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Phase")
                        .HasDatabaseName("IX_BrainstormSession_Phase");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_BrainstormSession_ProjectId");

                    b.ToTable("BrainstormSessions", (string)null);
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.ExecutionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Session_IsActive");

                    b.HasIndex("LastHeartbeat")
                        .HasDatabaseName("IX_Session_LastHeartbeat");

                    b.ToTable("ExecutionSessions");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("main");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Project_CreatedAt");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.RepositoryConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthenticationMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialIdentifier")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_RepositoryConfiguration_CreatedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_RepositoryConfiguration_IsActive");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_RepositoryConfiguration_Name");

                    b.ToTable("RepositoryConfigurations");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.StructuredLearningEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)");

                    b.Property<int>("HitCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastReferencedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceTaskId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("_tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_StructuredLearning_Category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_StructuredLearning_CreatedAt");

                    b.HasIndex("HitCount")
                        .HasDatabaseName("IX_StructuredLearning_HitCount");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_StructuredLearning_ProjectId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_StructuredLearning_Severity");

                    b.HasIndex("SourceTaskId")
                        .HasDatabaseName("IX_StructuredLearning_SourceTaskId");

                    b.ToTable("StructuredLearnings");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionPromise")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EstimatedComplexity")
                        .HasColumnType("integer");

                    b.Property<int>("IterationCount")
                        .HasColumnType("integer");

                    b.Property<string>("Learnings")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime?>("LearningsUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer");

                    b.Property<int>("ParallelGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Result")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<List<string>>("_dependencies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Dependencies");

                    b.PrimitiveCollection<List<string>>("_filesToModify")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("FilesToModify");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Task_CreatedAt");

                    b.HasIndex("CurrentSessionId")
                        .HasDatabaseName("IX_Task_SessionId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Tasks_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Task_Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.TaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CompletionPromiseFound")
                        .HasColumnType("boolean");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("ExecutionDuration")
                        .HasColumnType("interval");

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LlmResponse")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<string>("ModelId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("IX_TaskExecution_ExecutedAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_TaskExecution_SessionId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_TaskExecution_TaskId");

                    b.ToTable("TaskExecutions");
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.AnalysisIteration", b =>
                {
                    b.HasOne("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", null)
                        .WithMany("Iterations")
                        .HasForeignKey("CodeAnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", b =>
                {
                    b.OwnsOne("Daedalus.Domain.CodeAnalysis.AnalysisOutcome", "Outcome", b1 =>
                        {
                            b1.Property<Guid>("CodeAnalysisRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CommitShaFinal")
                                .HasColumnType("text")
                                .HasColumnName("CommitShaFinal");

                            b1.Property<bool>("HasFailedValidation")
                                .HasColumnType("boolean")
                                .HasColumnName("HasFailedValidation");

                            b1.Property<string>("PullRequestUrl")
                                .HasColumnType("text")
                                .HasColumnName("PullRequestUrl");

                            b1.Property<string>("ValidationResult")
                                .HasColumnType("jsonb")
                                .HasColumnName("ValidationResult");

                            b1.HasKey("CodeAnalysisRequestId");

                            b1.ToTable("CodeAnalysisRequests");

                            b1.WithOwner()
                                .HasForeignKey("CodeAnalysisRequestId");
                        });

                    b.OwnsOne("Daedalus.Domain.CodeAnalysis.CodeLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("CodeAnalysisRequestId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("EndLine")
                                .HasColumnType("integer")
                                .HasColumnName("EndLine");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("FilePath");

                            b1.Property<int?>("StartLine")
                                .HasColumnType("integer")
                                .HasColumnName("StartLine");

                            b1.HasKey("CodeAnalysisRequestId");

                            b1.ToTable("CodeAnalysisRequests");

                            b1.WithOwner()
                                .HasForeignKey("CodeAnalysisRequestId");
                        });

                    b.OwnsOne("Daedalus.Domain.CodeAnalysis.RepositoryReference", "Repository", b1 =>
                        {
                            b1.Property<Guid>("CodeAnalysisRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Branch")
                                .HasColumnType("text")
                                .HasColumnName("RepositoryBranch");

                            b1.Property<string>("CommitSha")
                                .HasColumnType("text")
                                .HasColumnName("CommitSha");

                            b1.Property<int>("Platform")
                                .HasColumnType("integer")
                                .HasColumnName("Platform");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("character varying(1024)")
                                .HasColumnName("RepositoryUrl");

                            b1.HasKey("CodeAnalysisRequestId");

                            b1.HasIndex("Url")
                                .HasDatabaseName("IX_CodeAnalysis_RepositoryUrl");

                            b1.ToTable("CodeAnalysisRequests");

                            b1.WithOwner()
                                .HasForeignKey("CodeAnalysisRequestId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Outcome")
                        .IsRequired();

                    b.Navigation("Repository")
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.AgentMessage", b =>
                {
                    b.HasOne("Daedalus.Domain.Entities.AgentSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.BrainstormMessage", b =>
                {
                    b.HasOne("Daedalus.Domain.Entities.BrainstormSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("BrainstormSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Task", b =>
                {
                    b.HasOne("Daedalus.Domain.Entities.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.TaskExecution", b =>
                {
                    b.HasOne("Daedalus.Domain.Entities.Task", null)
                        .WithMany("Executions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", b =>
                {
                    b.Navigation("Iterations");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.BrainstormSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Task", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
