// <auto-generated />
using System;
using System.Collections.Generic;
using Daedalus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Daedalus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209134036_AddMissingTaskColumns")]
    partial class AddMissingTaskColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.AnalysisIteration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<Guid>("CodeAnalysisRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<bool?>("CompilationSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PromptSent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("TestsPassed")
                        .HasColumnType("boolean");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CodeAnalysisRequestId")
                        .HasDatabaseName("IX_AnalysisIteration_RequestId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AnalysisIteration_CreatedAt");

                    b.ToTable("AnalysisIterations");
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<string>("CommitShaFinal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionPromise")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentIteration")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalReferences")
                        .HasColumnType("jsonb");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("FeatureBranchName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("HasFailedValidation")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAiResponse")
                        .HasColumnType("text");

                    b.Property<string>("LastPromptSent")
                        .HasColumnType("text");

                    b.Property<string>("LocalWorkTreePath")
                        .HasColumnType("text");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("PullRequestUrl")
                        .HasColumnType("text");

                    b.Property<string>("ReferencedDocuments")
                        .HasColumnType("jsonb");

                    b.Property<string>("RepositoryBranch")
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("StartLine")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CodeAnalysis_CreatedAt");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_CodeAnalysis_Priority");

                    b.HasIndex("RepositoryUrl")
                        .HasDatabaseName("IX_CodeAnalysis_RepositoryUrl");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_CodeAnalysis_Status");

                    b.ToTable("CodeAnalysisRequests");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.ExecutionSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Session_IsActive");

                    b.HasIndex("LastHeartbeat")
                        .HasDatabaseName("IX_Session_LastHeartbeat");

                    b.ToTable("ExecutionSessions");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionPromise")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("EstimatedComplexity")
                        .HasColumnType("integer");

                    b.Property<int>("IterationCount")
                        .HasColumnType("integer");

                    b.Property<string>("Learnings")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime?>("LearningsUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("integer");

                    b.Property<int>("ParallelGroup")
                        .HasColumnType("integer");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Result")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<List<string>>("_dependencies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("Dependencies");

                    b.PrimitiveCollection<List<string>>("_filesToModify")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("FilesToModify");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Task_CreatedAt");

                    b.HasIndex("CurrentSessionId")
                        .HasDatabaseName("IX_Task_SessionId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Tasks_ProjectId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Task_Status");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.TaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CompletionPromiseFound")
                        .HasColumnType("boolean");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("ExecutionDuration")
                        .HasColumnType("interval");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LlmResponse")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("IX_TaskExecution_ExecutedAt");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_TaskExecution_SessionId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("IX_TaskExecution_TaskId");

                    b.ToTable("TaskExecutions");
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.AnalysisIteration", b =>
                {
                    b.HasOne("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", "CodeAnalysisRequest")
                        .WithMany("Iterations")
                        .HasForeignKey("CodeAnalysisRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeAnalysisRequest");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Task", b =>
                {
                    b.HasOne("Daedalus.Domain.Entities.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.TaskExecution", b =>
                {
                    b.HasOne("Daedalus.Domain.Entities.Task", null)
                        .WithMany("Executions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Daedalus.Domain.CodeAnalysis.CodeAnalysisRequest", b =>
                {
                    b.Navigation("Iterations");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Daedalus.Domain.Entities.Task", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
